FIX2 - amend deposit function to include db support
tp859/newbank pull request #27
Opened 2022-04-08 21:48 UTC by tp859

Not sure what branch we should be merging into but I was working off revert-25-sprint5?

Would appreciate people's thoughts on this one as there's a few ways of doing it but in the end I opted to make the Account class a subclass of Customer as its methods needed access to its parent's Customer ID.

2022-04-09 10:41 UTC, shanpatt commented
This looks good to me, makes sense to make it a subclass.

Think this needs merging into sprint 5 though instead of the revert branch. As far as I can tell, the revert branch was made as a copy of main when I reverted the changes for DB and login (it was created automatically so really can't say for sure, but it doesn't have the read.me or .jar that Josh added as part of his fix).

2022-04-09 23:13 UTC, tp859 commented
Sounds good, though not sure if someone deleted the sprint5 branch unless I'm missing it?

2022-04-09 23:28 UTC, shanpatt commented
> Sounds good, though not sure if someone deleted the sprint5 branch unless I'm missing it?

I have literally no idea where the original sprint5 branch went. It was there after reverting changes because Joshua helped me pull it down, and I could see it earlier when I was trying to figure out the differences between it and the revert branch. Weird.  

I've pushed the copy of sprint5 I had locally now as sprint_5, so hopefully you can see that & we'll use that as the new sprint5 base.

2022-04-10 08:45 UTC, tp859 commented
Weird! Anyway I've amended this to merge with the sprint_5 branch, will do the same with the other one

2022-04-10 09:55 UTC, shanpatt approved these changes

2022-04-10 10:01 UTC, kp861 approved these changes

2022-04-10 10:40 UTC, Pookbros reviewed
This PR is going to delete the README file AND re-add the logins.csv file. Can you re-add one and delete the other @tp859 and commit again?

2022-04-10 10:44 UTC, Pookbros commented on server/NewBank.java
>      private void addTestData() {
We shouldn't need this test data now right? As they will be loaded in with the db... any point of these changes?

2022-04-10 11:21 UTC, Pookbros requested changes
Sorry Tom. These changes for FIX2 will have to re-done with sprint_5 as the base branch.

2022-04-11 10:15 UTC, closed without merging