Fix3 - added db support for withdraw function
tp859/newbank pull request #28
Opened 2022-04-09 08:39 UTC by tp859

This is assumes Account inheriting from Customer is ok as mentioned in Fix2 PR - if not I can amend.

2022-04-09 10:48 UTC, shanpatt commented
Looks good! Same as the other one, probably needs merging into sprint 5 instead of the revert branch.

2022-04-10 09:55 UTC, shanpatt approved these changes

2022-04-10 10:00 UTC, kp861 approved these changes

2022-04-10 11:20 UTC, Pookbros requested changes
Sorry Tom. These changes will have to be redone with sprint_5 as the base branch.

2022-04-11 11:45 UTC, closed without merging